#!/bin/sh

# 1. Stop the curent container and remove it
# 2. Pull the latest container from repository and run it.

sudo docker stop app_green           
sudo docker rm app_green
sudo docker pull localhost:5000/my_app:latest  
sudo docker run -p 3081:8080 -d --name app_green my_app
