rediscli: 
  image: anapsix/webdis
  links: 
    - ambassador:redis
  ports:
    - 7379:7379

ambassador:
  image: svendowideit/ambassador
  environment: 
    - REDIS_PORT_6379_TCP=tcp://162.243.80.149:6379
  expose:
   - "6379"
